### ISSUE TITLE
Cant convert VGG16 model

### ISSUE THREAD

**Issue by divamgupta** [MarcBS/keras#17]
I am trying to convert the Places CNN VGG16 model.

[Places CNN](http://places.csail.mit.edu/downloadCNN.html)
[Link To VGG16 prototxt and caffemodel ](http://places.csail.mit.edu/model/places205vgg.tar.gz)

I tried running

```
python caffe2keras.py -load_path '/root/places/places205VGG16' -prototxt 'deploy_10.prototxt' -caffemodel 'snapshot_iter_765280.caffemodel'
```

I got the following output

```
Using Theano backend.
Converting model...
CREATING MODEL
Printing the converted model:
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
conv1_1 (InputLayer)             (None, 3, 224, 224)   0                                            
____________________________________________________________________________________________________
relu1_1 (Activation)             (None, 3, 224, 224)   0           conv1_1[0][0]                    
____________________________________________________________________________________________________
conv1_2_zeropadding (ZeroPadding2(None, 3, 226, 226)   0           relu1_1[0][0]                    
____________________________________________________________________________________________________
conv1_2 (Convolution2D)          (None, 64, 224, 224)  1792        conv1_2_zeropadding[0][0]        
____________________________________________________________________________________________________
relu1_2 (Activation)             (None, 64, 224, 224)  0           conv1_2[0][0]                    
____________________________________________________________________________________________________
pool1 (MaxPooling2D)             (None, 64, 112, 112)  0           relu1_2[0][0]                    
____________________________________________________________________________________________________
conv2_1_zeropadding (ZeroPadding2(None, 64, 114, 114)  0           pool1[0][0]                      
____________________________________________________________________________________________________
conv2_1 (Convolution2D)          (None, 128, 112, 112) 73856       conv2_1_zeropadding[0][0]        
____________________________________________________________________________________________________
relu2_1 (Activation)             (None, 128, 112, 112) 0           conv2_1[0][0]                    
____________________________________________________________________________________________________
conv2_2_zeropadding (ZeroPadding2(None, 128, 114, 114) 0           relu2_1[0][0]                    
____________________________________________________________________________________________________
conv2_2 (Convolution2D)          (None, 128, 112, 112) 147584      conv2_2_zeropadding[0][0]        
____________________________________________________________________________________________________
relu2_2 (Activation)             (None, 128, 112, 112) 0           conv2_2[0][0]                    
____________________________________________________________________________________________________
pool2 (MaxPooling2D)             (None, 128, 56, 56)   0           relu2_2[0][0]                    
____________________________________________________________________________________________________
conv3_1_zeropadding (ZeroPadding2(None, 128, 58, 58)   0           pool2[0][0]                      
____________________________________________________________________________________________________
conv3_1 (Convolution2D)          (None, 256, 56, 56)   295168      conv3_1_zeropadding[0][0]        
____________________________________________________________________________________________________
relu3_1 (Activation)             (None, 256, 56, 56)   0           conv3_1[0][0]                    
____________________________________________________________________________________________________
conv3_2_zeropadding (ZeroPadding2(None, 256, 58, 58)   0           relu3_1[0][0]                    
____________________________________________________________________________________________________
conv3_2 (Convolution2D)          (None, 256, 56, 56)   590080      conv3_2_zeropadding[0][0]        
____________________________________________________________________________________________________
relu3_2 (Activation)             (None, 256, 56, 56)   0           conv3_2[0][0]                    
____________________________________________________________________________________________________
conv3_3_zeropadding (ZeroPadding2(None, 256, 58, 58)   0           relu3_2[0][0]                    
____________________________________________________________________________________________________
conv3_3 (Convolution2D)          (None, 256, 56, 56)   590080      conv3_3_zeropadding[0][0]        
____________________________________________________________________________________________________
relu3_3 (Activation)             (None, 256, 56, 56)   0           conv3_3[0][0]                    
____________________________________________________________________________________________________
pool3 (MaxPooling2D)             (None, 256, 28, 28)   0           relu3_3[0][0]                    
____________________________________________________________________________________________________
conv4_1_zeropadding (ZeroPadding2(None, 256, 30, 30)   0           pool3[0][0]                      
____________________________________________________________________________________________________
conv4_1 (Convolution2D)          (None, 512, 28, 28)   1180160     conv4_1_zeropadding[0][0]        
____________________________________________________________________________________________________
relu4_1 (Activation)             (None, 512, 28, 28)   0           conv4_1[0][0]                    
____________________________________________________________________________________________________
conv4_2_zeropadding (ZeroPadding2(None, 512, 30, 30)   0           relu4_1[0][0]                    
____________________________________________________________________________________________________
conv4_2 (Convolution2D)          (None, 512, 28, 28)   2359808     conv4_2_zeropadding[0][0]        
____________________________________________________________________________________________________
relu4_2 (Activation)             (None, 512, 28, 28)   0           conv4_2[0][0]                    
____________________________________________________________________________________________________
conv4_3_zeropadding (ZeroPadding2(None, 512, 30, 30)   0           relu4_2[0][0]                    
____________________________________________________________________________________________________
conv4_3 (Convolution2D)          (None, 512, 28, 28)   2359808     conv4_3_zeropadding[0][0]        
____________________________________________________________________________________________________
relu4_3 (Activation)             (None, 512, 28, 28)   0           conv4_3[0][0]                    
____________________________________________________________________________________________________
pool4 (MaxPooling2D)             (None, 512, 14, 14)   0           relu4_3[0][0]                    
____________________________________________________________________________________________________
conv5_1_zeropadding (ZeroPadding2(None, 512, 16, 16)   0           pool4[0][0]                      
____________________________________________________________________________________________________
conv5_1 (Convolution2D)          (None, 512, 14, 14)   2359808     conv5_1_zeropadding[0][0]        
____________________________________________________________________________________________________
relu5_1 (Activation)             (None, 512, 14, 14)   0           conv5_1[0][0]                    
____________________________________________________________________________________________________
conv5_2_zeropadding (ZeroPadding2(None, 512, 16, 16)   0           relu5_1[0][0]                    
____________________________________________________________________________________________________
conv5_2 (Convolution2D)          (None, 512, 14, 14)   2359808     conv5_2_zeropadding[0][0]        
____________________________________________________________________________________________________
relu5_2 (Activation)             (None, 512, 14, 14)   0           conv5_2[0][0]                    
____________________________________________________________________________________________________
conv5_3_zeropadding (ZeroPadding2(None, 512, 16, 16)   0           relu5_2[0][0]                    
____________________________________________________________________________________________________
conv5_3 (Convolution2D)          (None, 512, 14, 14)   2359808     conv5_3_zeropadding[0][0]        
____________________________________________________________________________________________________
relu5_3 (Activation)             (None, 512, 14, 14)   0           conv5_3[0][0]                    
____________________________________________________________________________________________________
pool5 (MaxPooling2D)             (None, 512, 7, 7)     0           relu5_3[0][0]                    
____________________________________________________________________________________________________
fc6_flatten (Flatten)            (None, 25088)         0           pool5[0][0]                      
____________________________________________________________________________________________________
fc6 (Dense)                      (None, 4096)          102764544   fc6_flatten[0][0]                
____________________________________________________________________________________________________
relu6 (Activation)               (None, 4096)          0           fc6[0][0]                        
____________________________________________________________________________________________________
drop6 (Dropout)                  (None, 4096)          0           relu6[0][0]                      
____________________________________________________________________________________________________
fc7 (Dense)                      (None, 4096)          16781312    drop6[0][0]                      
____________________________________________________________________________________________________
relu7 (Activation)               (None, 4096)          0           fc7[0][0]                        
____________________________________________________________________________________________________
drop7 (Dropout)                  (None, 4096)          0           relu7[0][0]                      
____________________________________________________________________________________________________
fc8 (Dense)                      (None, 205)           839885      drop7[0][0]                      
____________________________________________________________________________________________________
prob (Activation)                (None, 205)           0           fc8[0][0]                        
====================================================================================================
Total params: 135063501
____________________________________________________________________________________________________

LOADING WEIGHTS



Traceback (most recent call last):
  File "caffe2keras.py", line 45, in <module>
    main(args)
  File "caffe2keras.py", line 34, in main
    model = convert.caffe_to_keras(args.load_path+'/'+args.prototxt, args.load_path+'/'+args.caffemodel, debug=args.debug)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/caffe/convert.py", line 64, in caffe_to_keras
    load_weights(model, weights)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/caffe/convert.py", line 455, in load_weights
    model.get_layer(layer.name).set_weights(weights[layer.name])
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/engine/topology.py", line 879, in set_weights
    ' weights. Provided weights: ' + str(weights)[:50] + '...')
Exception: You called `set_weights(weights)` on layer "conv1_1" with a  weight list of length 2, but the layer was expecting 0 weights. Provided weights: [array([[[[ -6.61635473e-02,  -6.69440255e-02,  -2...
```

**Comment by sfrodrigues** [comment]
Hey divamgupta,

Like explained here (https://github.com/MarcBS/keras/blob/master/keras/caffe/README.md) you need to include the following in your prototxt:

name: "nameofthenetwork"
input: "data"
input_dim: 10
input_dim: 3
input_dim: xxx
input_dim: xxx
layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
}

and them comes the first layer of the network.

**Comment by divamgupta** [comment]
Yes that worked
