### ISSUE TITLE
Recurrent dropout is broken in (at least) AttGRUCond

### ISSUE THREAD

**Issue by lvapeab** [MarcBS/keras#35]
Traceback (most recent call last):
  File "main.py", line 354, in <module>
    train_model(parameters)
  File "main.py", line 37, in train_model
    store_path=params['STORE_PATH'])
  File "/home/machirio/NMT/nmt-keras/model_zoo.py", line 102, in __init__
    eval('self.' + type + '(params)')
  File "<string>", line 1, in <module>
  File "/home/machirio/NMT/nmt-keras/model_zoo.py", line 364, in GroundHogModel
    rnn_output = sharedAttRNNCond(input_attentional_decoder)
  File "/home/machirio/NMT/keras/keras/engine/topology.py", line 569, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/machirio/NMT/keras/keras/engine/topology.py", line 632, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/machirio/NMT/keras/keras/engine/topology.py", line 170, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/home/machirio/NMT/keras/keras/layers/recurrent.py", line 1340, in call
    constants, B_V = self.get_constants(state_below, mask[1])
  File "/home/machirio/NMT/keras/keras/layers/recurrent.py", line 1447, in get_constants
    input_shape = self.input_spec[0][0].shape

**Comment by lvapeab** [comment]
Fixed (d7191d422bfe81ec1f8125950a7b45a15caf6e42).
