### ISSUE TITLE
no module named 'keras_applications' 

### ISSUE THREAD

**Issue by SANTO-P** [MarcBS/keras#57]
Traceback (most recent call last):
  File "caffe2keras.py", line 1, in <module>
    import keras.caffe.convert as convert
  File "/home/santosh/Music/poshaq/landmark_detection/new/keras/keras/__init__.py", line 5, in <module>
    from . import applications
  File "/home/santosh/Music/poshaq/landmark_detection/new/keras/keras/applications/__init__.py", line 11, in <module>
    import keras_applications
ImportError: No module named 'keras_applications'

**Comment by lvapeab** [comment]
The Keras Team recently removed the modules `keras_applications`and `keras_preprocessing` from the `Keras` repo and released them as pip packages. You should do:

`pip install keras_applications keras_preprocessing`

Cheers
